### PR TITLE
Rebase monasca fork on 4 1 0

### PR DESCRIPTION
**Pull request by dougszumski**
Needs testing before merge. Remarkably, this didn't have many conflicts. The motivation is to add support for ES 5.

### CODE REVIEW

**Comment by matrixik** [comment]
Hi, thank you for doing it.
Unfortunately when I try to build it I'm getting error:
```
go install -v ./pkg/cmd/grafana-server
import cycle not allowed
package github.com/grafana/grafana/pkg/cmd/grafana-server
	imports github.com/grafana/grafana/pkg/api
	imports github.com/grafana/grafana/pkg/api/cloudwatch
	imports github.com/grafana/grafana/pkg/middleware
	imports github.com/grafana/grafana/pkg/login
	imports github.com/grafana/grafana/pkg/api/keystone
	imports github.com/grafana/grafana/pkg/middleware
exit status 1
exit status 1
```

**Comment by dougszumski** [comment]
@matrixik yeah - the cycle was introduced by an LDAP patch. I have some more work to push on this. I managed to rebase on 4.6.5 in the end, and I've got it to build. I just need to test it!

**Comment by dougszumski** [comment]
If you're interested in being a guinea pig here's the branch re-based on the 4.6.5 release: https://github.com/stackhpc/grafana/tree/rebase_monasca_fork_on_4_6_5

**Comment by matrixik** [comment]
Still no bueno with 4.6.5
```
github.com/grafana/grafana/pkg/tsdb/opentsdb
# github.com/grafana/grafana/pkg/tsdb/mysql
pkg/tsdb/mysql/mysql.go:76: rows.ColumnTypes undefined (type *core.Rows has no field or method ColumnTypes)
pkg/tsdb/mysql/mysql.go:102: undefined: sql.ColumnType
github.com/grafana/grafana/pkg/tsdb/postgres
github.com/grafana/grafana/pkg/tsdb/prometheus
# github.com/grafana/grafana/pkg/tsdb/postgres
pkg/tsdb/postgres/postgres.go:101: rows.ColumnTypes undefined (type *core.Rows has no field or method ColumnTypes)
github.com/grafana/grafana/pkg/components/imguploader
github.com/grafana/grafana/vendor/github.com/uber/jaeger-client-go/internal/baggage/remote
github.com/grafana/grafana/vendor/github.com/uber/jaeger-client-go/rpcmetrics
github.com/grafana/grafana/pkg/services/alerting
github.com/grafana/grafana/vendor/github.com/uber/jaeger-client-go/config
github.com/grafana/grafana/pkg/tracing
github.com/grafana/grafana/pkg/api
github.com/grafana/grafana/pkg/services/alerting/conditions
github.com/grafana/grafana/pkg/services/alerting/notifiers
# github.com/grafana/grafana/pkg/api
pkg/api/http_server.go:66: undefined: http.ErrServerClosed
pkg/api/http_server.go:72: undefined: http.ErrServerClosed
pkg/api/http_server.go:97: hs.httpSrv.Shutdown undefined (type *http.Server has no field or method Shutdown)
github.com/grafana/grafana/vendor/github.com/aws/aws-sdk-go/service/ec2/ec2iface
github.com/grafana/grafana/pkg/tsdb/cloudwatch
# github.com/grafana/grafana/pkg/tsdb/cloudwatch
pkg/tsdb/cloudwatch/cloudwatch.go:198: undefined: sort.Slice
pkg/tsdb/cloudwatch/cloudwatch.go:327: undefined: sort.Slice
pkg/tsdb/cloudwatch/metric_find_query.go:356: undefined: sort.Slice
pkg/tsdb/cloudwatch/metric_find_query.go:447: undefined: sort.Slice
github.com/grafana/grafana/pkg/services/sqlstore/migrator
github.com/grafana/grafana/pkg/services/sqlstore/migrations
github.com/grafana/grafana/pkg/services/sqlstore
exit status 2
exit status 1
```

**Comment by dougszumski** [comment]
Hmm, I don't remember hitting that. I've got half baked runes for a Kolla Docker image. When I've got it to build in that environment I'll ping you - thanks for trying.

**Comment by dougszumski** [comment]
This is superseded by the 4.2 PR.

**Pull request closed without merging**
